# Generated by Django 3.1.4 on 2020-12-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JamieBlog', '0003_auto_20201223_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
