# Generated by Django 3.1.4 on 2020-12-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JamieBlog', '0004_auto_20201223_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
